### ISSUE TITLE
 Multi GPU mode is stuck at the beginning

### ISSUE THREAD

**Issue by liygzting** [affjljoo3581/GPT2#4]
hi @affjljoo3581  
Thank you very much for your work
when I run for demo,it stuck. but no --gpus it works well  [only on my first gpu]
[root@gpu02]:~/kb/src# python -m gpt2 train --train_corpus           ../build/corpus.train.txt \
>                      --eval_corpus            ../build/corpus.test.txt \
>                      --vocab_path             ../build/vocab.txt \
>                      --dims                   1024 \
>                      --batch_train            128 \
>                      --batch_eval             128 \
>                      --seq_len                64 \
>                      --total_steps            3000 \
>                      --eval_steps             500 \
>                      --save_steps             3000 \
>                      --gpus                   4
                     --save_checkpoint_path   ckpt-gpt2.pth \
                     --save_model_path        gpt2-pretrained.pth

Train GPT-2 model:   0%|                                                                                                                      | 0/3000 [00:00<?, ?it/s]
How to fix it so that the program goes on？

**Comment by affjljoo3581** [comment]
First of all, you did not append the backslash (`\`) to the end of the `--gpus 4` parameter line. Because of that, the arguments after the `--gpu 4` line may be ignored. I think it is not a solution, but show me the result after fixing the bug first.

**Comment by liygzting** [comment]
sorry,This is the format of the display
`python -m gpt2 train --train_corpus           ../build/corpus.train.txt \
                     --eval_corpus            ../build/corpus.test.txt \
                     --vocab_path             ../build/vocab.txt \
                     --dims                   1024 \
                     --batch_train            128 \
                     --batch_eval             128 \
                     --seq_len                64 \
                     --total_steps            3000 \
                     --eval_steps             500 \
                     --save_steps             3000 \
                     --gpus                   4 \
                     --save_checkpoint_path   ckpt-gpt2.pth \
                     --save_model_path        gpt2-pretrained.pth`

and ENTER for run
it still stuck，as follows
>Train GPT-2 model:   0%|                                                                                                                      | 0/3000 [00:00<?, ?it/s]

when run nvidia-smi,

The multi GPU seems to be up, but it's stuck
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0   3542447      C   /root/anaconda3/bin/python                  2315MiB |
|    1   3542448      C   /root/anaconda3/bin/python                  2320MiB |
|    2   3542449      C   /root/anaconda3/bin/python                  2315MiB |
|    3   3542450      C   /root/anaconda3/bin/python                  2320MiB |
+-----------------------------------------------------------------------------+

**Comment by liygzting** [comment]
> Thu Nov 12 08:40:04 2020                                                                                                                                               
+-----------------------------------------------------------------------------+                                                                                        
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |                                                                                        
|-------------------------------+----------------------+----------------------+                                                                                        
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 00000000:0A:00.0 Off |                  Off |
| N/A   38C    P0    48W / 150W |   2327MiB /  8129MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | 00000000:0B:00.0 Off |                  Off |
| N/A   36C    P0    46W / 150W |   2331MiB /  8129MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M60           Off  | 00000000:86:00.0 Off |                  Off |
| N/A   38C    P0    47W / 150W |   2327MiB /  8129MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M60           Off  | 00000000:87:00.0 Off |                  Off |
| N/A   33C    P0    46W / 150W |   2331MiB /  8129MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0   3542447      C   /root/anaconda3/bin/python                  2315MiB |
|    1   3542448      C   /root/anaconda3/bin/python                  2320MiB |
|    2   3542449      C   /root/anaconda3/bin/python                  2315MiB |
|    3   3542450      C   /root/anaconda3/bin/python                  2320MiB |
+-----------------------------------------------------------------------------+

**Comment by liygzting** [comment]
file:///home/liyg/图片/1.png

**Comment by liygzting** [comment]
![1](https://user-images.githubusercontent.com/73510109/98881204-6ca6e900-24c4-11eb-944a-a27b9d0cf2a9.png)

**Comment by liygzting** [comment]
![gpu status](https://user-images.githubusercontent.com/73510109/98881230-7c263200-24c4-11eb-9562-6d7cd7ec20c6.png)

**Comment by liygzting** [comment]
![1](https://user-images.githubusercontent.com/73510109/98882063-69acf800-24c6-11eb-8eb4-ffa630a1c069.png)

**Comment by liygzting** [comment]
!(https://user-images.githubusercontent.com/73510109/98882087-7c273180-24c6-11eb-9cf0-f721bfb43381.png)

**Comment by liygzting** [comment]
![gpu status](https://user-images.githubusercontent.com/73510109/98882168-a842b280-24c6-11eb-9931-24f78659e483.png)

**Comment by affjljoo3581** [comment]
How long did you wait for the freeze? Due to the distributed training environment, it usually spends a few minutes before start training. In my case, 2x **V100** required about 2 to 3 minutes.

**Comment by liygzting** [comment]
It's been running for hours, so I canceled it
However, single GPU can run at a speed of 1.5it/s

**Comment by affjljoo3581** [comment]
What about two GPUs? Can you show me the result with 2 and 3 GPUs?

**Comment by liygzting** [comment]
I've tested that --gpus from 2 to 4
There was no improvement
![2](https://user-images.githubusercontent.com/73510109/99047714-8da83080-25cf-11eb-88f4-8c915c173942.png)
![3](https://user-images.githubusercontent.com/73510109/99047725-913bb780-25cf-11eb-941c-efcbcc153e6d.png)

**Comment by affjljoo3581** [comment]
I ran this model on 2x **V100**s. I think distributed reduction would be the problem. Can you check if the GPU memory usage increases depending on the batch size?

**Comment by affjljoo3581** [comment]
And check if tcp port 8000 is available as well.

**Comment by liygzting** [comment]
the GPU memory usage  looks like OK when i set batch size is 64
and port 8000 is available
![n](https://user-images.githubusercontent.com/73510109/99201341-7f336200-27e5-11eb-82a1-569130e64397.png)

**Comment by liygzting** [comment]
I think it is ommunication problem of multi GPU graphics card
[Communication problem of multi GPU graphics card](http://www.caffecn.cn/?/question/406)
When I set CUDA_VISIBLE_DEVICES=0,1 and --gpus 2 it don't work
But I set CUDA_VISIBLE_DEVICES=0,2 and --gpus 2 it works
Maybe 0 and 2 or 1 and 3 are able to communicate

**Comment by liygzting** [comment]
I find Volatile GPU-Util is too low, Most of the time it is 10% even 0%
0% -> 10% -> 99% 
How can I set it to work like DataLoader set num_workers

**Comment by affjljoo3581** [comment]
In my case, the GPU utilization was over 80% with my 2x **V100**s. Although my `Dataset` class does not spawn the worker threads for fetching data from the corpus, it actually does not matter for the performance with the proper system (sufficient CPUs and RAMs) and suitable vocabulary size. How about testing the bottleneck of my `Dataset` loader? Change the
https://github.com/affjljoo3581/GPT2/blob/71ebf9105be828337463cd34bbf6252414620aae/src/gpt2/data/corpus.py#L28-L50
function code as below:
```python
    def _fetch_one(self) -> Dict[str, List[int]]:
        indices += [0] * (self.seq_len + 1)
        return {'input': indices[:-1], 'output': indices[1:]}
```

**Comment by liygzting** [comment]
thanks very much
I think this may be another point I need to know
At present, my GPU is busy running
At the same time, I need to understand gpt2 deeply
