### ISSUE TITLE
Which kind of tokenizer do you use? It looks like WordPiece, not BPE.

### ISSUE THREAD

**Issue by Suxyuuu** [affjljoo3581/GPT2#9]
OpenAI's GPT-2 implementation uses **BPE** to make tokenizer, which needs 2 files: one is a .json file contains vocabulary, another is a .txt file contains merges. 
Your implementation only uses one `vocab.txt` file, and some vocabulary may start with '##', which implys from your `tokenization.py`.
So do you use **WordPiece** not **BPE**?
(not English native speaker, sorry for my poor English...)

**Comment by affjljoo3581** [comment]
I used WordPiece which is specified on [this link](https://github.com/affjljoo3581/Expanda/blob/5516ed9c7ae63b51bf9cae6083429eca3b36d34e/src/expanda/tokenization.py#L67).
